[package]
name = "mtop-client"
version = "0.8.0"
authors = ["Nick Pillitteri"]
description = "Memcached client for mtop"
homepage = "https://github.com/56quarters/mtop"
repository = "https://github.com/56quarters/mtop"
readme = "../README.md"
license = "GPL-3.0+"
keywords = ["top", "memcached"]
edition = "2021"

[dependencies]
pin-project-lite = "0.2.13"
rustls-pemfile = "2.0.0"
rustls-webpki = "0.102.0"
tokio = { version = "1.14.0", features = ["full"] }
tokio-rustls = { version = "0.25.0" }
tracing = "0.1.11"
urlencoding = "2.1.2"
webpki-roots = "0.26.0"

[lib]
name = "mtop_client"
path = "src/lib.rs"
