[workspace]

[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2024"
license = "GPL-3.0+"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4.0", features = ["arbitrary-derive"] }
mtop = { path = "../mtop" }
mtop-client = { path = "../mtop-client" }
tokio = { version = "1.14.0", features = ["full"] }

[[bin]]
name = "fuzz_target_dns_message"
path = "fuzz_targets/dns_message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_dns_name_bytes"
path = "fuzz_targets/dns_name_bytes.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_dns_name_str"
path = "fuzz_targets/dns_name_str.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_memcached_get"
path = "fuzz_targets/memcached_get.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_memcached_metas"
path = "fuzz_targets/memcached_metas.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_url_decode"
path = "fuzz_targets/url_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_url_encode"
path = "fuzz_targets/url_encode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_memcached_stats"
path = "fuzz_targets/memcached_stats.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_target_mtop_duration"
path = "fuzz_targets/mtop_duration.rs"
test = false
doc = false
bench = false
